version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Best practice (Windows line endings different to Unix/Linux)
  - cmd: git config --global core.autocrlf true
install:
 
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Threenine.Data/Threenine.Data.csproj --verbosity m
build_script:
  
  - cmd: dotnet build ./Threenine.Data/Threenine.Data.csproj
after_build:
  # For once the build has completed

on_finish :
  # any cleanup in here
deploy: off