version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Best practice (Windows line endings different to Unix/Linux)
  - cmd: git config --global core.autocrlf true
install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Threenine.Data/Threenine.Data.csproj --verbosity m
build_script:
    - cmd: dotnet build ./Threenine.Data/Threenine.Data.csproj
    - cmd: dotnet pack  -c Release /p:PackageVersion=1.0.3 
artifacts:
- path: ./Threenine.Data/bin/Release/*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  server: https://www.myget.org/F/threenine/api/v2/package
  api_key:
    secure: 4da8b7a9-9b60-479a-8194-3cc7822a748a
  skip_symbols: true