version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Best practice (Windows line endings different to Unix/Linux)
  - cmd: git config --global core.autocrlf true
install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Threenine.Data/Threenine.Data.csproj --verbosity m
build_script:
    - cmd: dotnet build ./Threenine.Data/Threenine.Data.csproj -c Release
    - cmd: dotnet pack  -c Release /p:PackageVersion=1.0.{build} 
artifacts:
- path: ./Threenine.Data/bin/Release/*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  server: https://www.myget.org/F/threenine/api/v2/package
  api_key:
    secure: FU841XC5Cujzqo+j12T4vI0bngL5ScxwCK8VT5OuuYi7aWw+0utt+Bpv3/5tr82Q
  skip_symbols: true